// Written by James Mu
// Template from Dr. Palmeri

@startuml

[*] -> init

state init {
    init: set sampling rate
    init: set LRI
}

state acquiring {
    acquiring: acquire amplified electrogram
    acquiring: acquire comparator output
}

state processing {
    processing: detect ventricular depolarization
    processing: determine time since last depolarization
    processing: calculate instantaneous HR
}

state pacing {
    pacing: trigger pacemaker
}

state error {
    error: safe mode
}

init -> acquiring : init complete
init -d-> error : init failed
acquiring -> processing : signals acquired
processing -u-> pacing : HR > LRI
processing -> acquiring : HR < LRI
pacing -> acquiring : pacing complete
acquiring -d-> error : signal acquisition failed
error -> acquiring : reset error
error -> [*] : time out

@enduml