// Written by James Mu
// Template from Dr. Palmeri

@startuml
!theme mars

[*] -> init

state init {
    init: set sampling rate
    init: set LRI
    init: acquire initial Vcomp
}

state acquiring {
    acquiring: read ECG amp signal
    acquiring: read comparator output
}

state processing {
    processing: detect QRS from comparator
    processing: calculate R-R interval
    processing: update HR
    processing: set new Vcomp
}

state pacing {
    pacing: deliver stimulus pulse
}

state error {
    error: enter safe mode
}

init -> acquiring : init complete
init -d-> error : init failed

acquiring -> processing : new sample
acquiring -d-> error : sampling failed

processing -> acquiring : R-R < LRI
processing --> pacing : R-R > LRI

pacing -> acquiring : pulse delivered

error -> acquiring : error cleared
error -d-> [*] : time out

@enduml